services:
  gunicorn:
    container_name: gunicorn
    build: Services/Gunicorn
    restart: always
    env_file: .env
    volumes:
      - django_data:/app/Project
    depends_on:
      postgres:
        condition: service_healthy

  uvicorn:
    container_name: uvicorn
    build: Services/Uvicorn
    restart: always
    env_file: .env
    volumes:
      - django_data:/app/Project
    depends_on:
      - postgres

  postgres:
    container_name: database
    image: postgres:16.1-alpine3.18
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval:  5s
      timeout:  5s
      retries:  5

  nginx:
    container_name: nginx
    build: Services/NginxReverseProxy/
    restart: always
    env_file: .env
    ports:
    - "8080:8080"
    volumes:
      - django_static:/var/lib/nginx/static/
      - django_media:/var/lib/nginx/avatars/
    depends_on:
      - gunicorn
      - uvicorn

volumes:
  postgres_data:
    name: postgres_data

  django_data:
    name: django_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: Django_data

  django_static:
    name: django_static
    driver: local
    driver_opts:
      type: none
      o: bind
      device: Django_data/staticfiles

  django_media:
    name: django_media
    driver: local
    driver_opts:
      type: none
      o: bind
      device: Django_data/avatars
