services:
  django:
    container_name: Django
    restart: always
    build: Backend/Django
    env_file: .env
    volumes:
      - django_data:/app/backend
    ports:
      - "8080:8000"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: Database
    image: postgres:16.1-alpine3.19
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
    name: postgres_data

  django_data:
    name: django_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: Backend/Django/project_backend
