services:
  gunicorn:
    container_name: Gunicorn
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    volumes:
      - django_data:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    container_name: Database
    image: postgres:16.1-alpine3.19
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

network:
  default:
    www_network:
      driver: bridge

volumes:
  postgres_data:
    name: postgres_data

  django_data:
    name: django_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: project_backend
