services:
  django:
    container_name: Django
    restart: always
    build: Backend/Django
    env_file: .env
    volumes:
      - django_data:/app/backend
    ports:
      - "8080:8000"

  postgres:
    container_name: database
    image: postgres:16.1-alpine3.18
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    container_name: nginx
    build: NginxReverseProxy/
    restart: always
    env_file: .env
    ports:
    - "8080:8080"
    volumes:
      - django_static:/var/lib/nginx/

volumes:
  postgres_data:
    name: postgres_data

  django_data:
    name: django_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: Backend/Django/project_backend
